name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for Azure OIDC
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create short SHA
      id: short_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/{{REPO_NAME}}
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=v${{ github.run_number }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=${{ steps.short_sha.outputs.sha }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Deploy only on main branch
    - name: Azure Login with OIDC
      if: github.ref == 'refs/heads/main'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Deploy to Azure Container Apps
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying to Azure Container Apps..."
        
        az containerapp update \
          --name {{AZURE_APP_NAME}} \
          --resource-group {{AZURE_RESOURCE_GROUP}} \
          --image ghcr.io/${{ github.repository_owner }}/{{REPO_NAME}}:latest
        
        echo "✅ Deployment completed successfully!"
        
    - name: Get App URL
      if: github.ref == 'refs/heads/main'
      run: |
        APP_URL=$(az containerapp show \
          --name {{AZURE_APP_NAME}} \
          --resource-group {{AZURE_RESOURCE_GROUP}} \
          --query 'properties.configuration.ingress.fqdn' \
          --output tsv)
        
        echo "🌐 Application URL: https://$APP_URL"
        echo "📦 Image: ghcr.io/${{ github.repository_owner }}/{{REPO_NAME}}:latest"
        echo "🏷️ Build: v${{ github.run_number }}"