name: Build and Deploy to Azure (Private)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry (Private)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}  # Uses PAT instead of GITHUB_TOKEN
        
    - name: Create short SHA
      id: short_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/{{REPO_NAME}}
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=v${{ github.run_number }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=${{ steps.short_sha.outputs.sha }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          
    - name: Build and push Docker image (Private)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Deploy only on main branch
    - name: Azure Login with OIDC
      if: github.ref == 'refs/heads/main'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Configure private registry access
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🔐 Configuring private registry access..."
        
        az containerapp registry set \
          --name ${{ secrets.AZURE_APP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --server ghcr.io \
          --username ${{ github.actor }} \
          --password ${{ secrets.GHCR_TOKEN }}
        
    - name: Deploy to Azure Container Apps (Private)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying private image to Azure..."
        
        az containerapp update \
          --name ${{ secrets.AZURE_APP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image ghcr.io/${{ github.repository_owner }}/{{REPO_NAME}}:latest
        
        echo "✅ Private deployment completed!"